// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/controlplane.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkMode int32

const (
	NetworkMode_NETWORK_MODE_UNSPECIFIED NetworkMode = 0 // Defaults to HOST
	NetworkMode_NETWORK_MODE_HOST        NetworkMode = 1
	NetworkMode_NETWORK_MODE_BRIDGE      NetworkMode = 2
)

// Enum value maps for NetworkMode.
var (
	NetworkMode_name = map[int32]string{
		0: "NETWORK_MODE_UNSPECIFIED",
		1: "NETWORK_MODE_HOST",
		2: "NETWORK_MODE_BRIDGE",
	}
	NetworkMode_value = map[string]int32{
		"NETWORK_MODE_UNSPECIFIED": 0,
		"NETWORK_MODE_HOST":        1,
		"NETWORK_MODE_BRIDGE":      2,
	}
)

func (x NetworkMode) Enum() *NetworkMode {
	p := new(NetworkMode)
	*p = x
	return p
}

func (x NetworkMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_controlplane_proto_enumTypes[0].Descriptor()
}

func (NetworkMode) Type() protoreflect.EnumType {
	return &file_api_proto_controlplane_proto_enumTypes[0]
}

func (x NetworkMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkMode.Descriptor instead.
func (NetworkMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{0}
}

type TraefikConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enable              bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Host                string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Entrypoint          string                 `protobuf:"bytes,3,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	EnableSsl           bool                   `protobuf:"varint,4,opt,name=enable_ssl,json=enableSsl,proto3" json:"enable_ssl,omitempty"`
	SslHost             string                 `protobuf:"bytes,5,opt,name=ssl_host,json=sslHost,proto3" json:"ssl_host,omitempty"`
	CertResolver        string                 `protobuf:"bytes,6,opt,name=cert_resolver,json=certResolver,proto3" json:"cert_resolver,omitempty"`
	HealthCheckPath     string                 `protobuf:"bytes,7,opt,name=health_check_path,json=healthCheckPath,proto3" json:"health_check_path,omitempty"`
	HealthCheckInterval string                 `protobuf:"bytes,8,opt,name=health_check_interval,json=healthCheckInterval,proto3" json:"health_check_interval,omitempty"`
	PathPrefix          string                 `protobuf:"bytes,9,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Middlewares         []string               `protobuf:"bytes,10,rep,name=middlewares,proto3" json:"middlewares,omitempty"`
	CustomLabels        map[string]string      `protobuf:"bytes,11,rep,name=custom_labels,json=customLabels,proto3" json:"custom_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TraefikConfig) Reset() {
	*x = TraefikConfig{}
	mi := &file_api_proto_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraefikConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraefikConfig) ProtoMessage() {}

func (x *TraefikConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraefikConfig.ProtoReflect.Descriptor instead.
func (*TraefikConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *TraefikConfig) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *TraefikConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TraefikConfig) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *TraefikConfig) GetEnableSsl() bool {
	if x != nil {
		return x.EnableSsl
	}
	return false
}

func (x *TraefikConfig) GetSslHost() string {
	if x != nil {
		return x.SslHost
	}
	return ""
}

func (x *TraefikConfig) GetCertResolver() string {
	if x != nil {
		return x.CertResolver
	}
	return ""
}

func (x *TraefikConfig) GetHealthCheckPath() string {
	if x != nil {
		return x.HealthCheckPath
	}
	return ""
}

func (x *TraefikConfig) GetHealthCheckInterval() string {
	if x != nil {
		return x.HealthCheckInterval
	}
	return ""
}

func (x *TraefikConfig) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *TraefikConfig) GetMiddlewares() []string {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

func (x *TraefikConfig) GetCustomLabels() map[string]string {
	if x != nil {
		return x.CustomLabels
	}
	return nil
}

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Replicas      int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Cpu           float64                `protobuf:"fixed64,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int64                  `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Traefik       *TraefikConfig         `protobuf:"bytes,8,opt,name=traefik,proto3" json:"traefik,omitempty"`
	NetworkMode   NetworkMode            `protobuf:"varint,9,opt,name=network_mode,json=networkMode,proto3,enum=controlplane.NetworkMode" json:"network_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_api_proto_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *DeployRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DeployRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *DeployRequest) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *DeployRequest) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *DeployRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *DeployRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DeployRequest) GetTraefik() *TraefikConfig {
	if x != nil {
		return x.Traefik
	}
	return nil
}

func (x *DeployRequest) GetNetworkMode() NetworkMode {
	if x != nil {
		return x.NetworkMode
	}
	return NetworkMode_NETWORK_MODE_UNSPECIFIED
}

type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_api_proto_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *DeployResponse) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeployResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeployResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *DeleteRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_controlplane_proto protoreflect.FileDescriptor

const file_api_proto_controlplane_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/controlplane.proto\x12\fcontrolplane\"\xf2\x03\n" +
	"\rTraefikConfig\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x03 \x01(\tR\n" +
	"entrypoint\x12\x1d\n" +
	"\n" +
	"enable_ssl\x18\x04 \x01(\bR\tenableSsl\x12\x19\n" +
	"\bssl_host\x18\x05 \x01(\tR\asslHost\x12#\n" +
	"\rcert_resolver\x18\x06 \x01(\tR\fcertResolver\x12*\n" +
	"\x11health_check_path\x18\a \x01(\tR\x0fhealthCheckPath\x122\n" +
	"\x15health_check_interval\x18\b \x01(\tR\x13healthCheckInterval\x12\x1f\n" +
	"\vpath_prefix\x18\t \x01(\tR\n" +
	"pathPrefix\x12 \n" +
	"\vmiddlewares\x18\n" +
	" \x03(\tR\vmiddlewares\x12R\n" +
	"\rcustom_labels\x18\v \x03(\v2-.controlplane.TraefikConfig.CustomLabelsEntryR\fcustomLabels\x1a?\n" +
	"\x11CustomLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x03\n" +
	"\rDeployRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x01R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x03R\x06memory\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12?\n" +
	"\x06labels\x18\a \x03(\v2'.controlplane.DeployRequest.LabelsEntryR\x06labels\x125\n" +
	"\atraefik\x18\b \x01(\v2\x1b.controlplane.TraefikConfigR\atraefik\x12<\n" +
	"\fnetwork_mode\x18\t \x01(\x0e2\x19.controlplane.NetworkModeR\vnetworkMode\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\x0eDeployResponse\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"W\n" +
	"\rDeleteRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*[\n" +
	"\vNetworkMode\x12\x1c\n" +
	"\x18NETWORK_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11NETWORK_MODE_HOST\x10\x01\x12\x17\n" +
	"\x13NETWORK_MODE_BRIDGE\x10\x022\xae\x01\n" +
	"\fControlPlane\x12N\n" +
	"\x11DeployApplication\x12\x1b.controlplane.DeployRequest\x1a\x1c.controlplane.DeployResponse\x12N\n" +
	"\x11DeleteApplication\x12\x1b.controlplane.DeleteRequest\x1a\x1c.controlplane.DeleteResponseB0Z.github.com/iuliansafta/control-plane/api/protob\x06proto3"

var (
	file_api_proto_controlplane_proto_rawDescOnce sync.Once
	file_api_proto_controlplane_proto_rawDescData []byte
)

func file_api_proto_controlplane_proto_rawDescGZIP() []byte {
	file_api_proto_controlplane_proto_rawDescOnce.Do(func() {
		file_api_proto_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_controlplane_proto_rawDesc), len(file_api_proto_controlplane_proto_rawDesc)))
	})
	return file_api_proto_controlplane_proto_rawDescData
}

var file_api_proto_controlplane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_controlplane_proto_goTypes = []any{
	(NetworkMode)(0),       // 0: controlplane.NetworkMode
	(*TraefikConfig)(nil),  // 1: controlplane.TraefikConfig
	(*DeployRequest)(nil),  // 2: controlplane.DeployRequest
	(*DeployResponse)(nil), // 3: controlplane.DeployResponse
	(*DeleteRequest)(nil),  // 4: controlplane.DeleteRequest
	(*DeleteResponse)(nil), // 5: controlplane.DeleteResponse
	nil,                    // 6: controlplane.TraefikConfig.CustomLabelsEntry
	nil,                    // 7: controlplane.DeployRequest.LabelsEntry
}
var file_api_proto_controlplane_proto_depIdxs = []int32{
	6, // 0: controlplane.TraefikConfig.custom_labels:type_name -> controlplane.TraefikConfig.CustomLabelsEntry
	7, // 1: controlplane.DeployRequest.labels:type_name -> controlplane.DeployRequest.LabelsEntry
	1, // 2: controlplane.DeployRequest.traefik:type_name -> controlplane.TraefikConfig
	0, // 3: controlplane.DeployRequest.network_mode:type_name -> controlplane.NetworkMode
	2, // 4: controlplane.ControlPlane.DeployApplication:input_type -> controlplane.DeployRequest
	4, // 5: controlplane.ControlPlane.DeleteApplication:input_type -> controlplane.DeleteRequest
	3, // 6: controlplane.ControlPlane.DeployApplication:output_type -> controlplane.DeployResponse
	5, // 7: controlplane.ControlPlane.DeleteApplication:output_type -> controlplane.DeleteResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_controlplane_proto_init() }
func file_api_proto_controlplane_proto_init() {
	if File_api_proto_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_controlplane_proto_rawDesc), len(file_api_proto_controlplane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_controlplane_proto_goTypes,
		DependencyIndexes: file_api_proto_controlplane_proto_depIdxs,
		EnumInfos:         file_api_proto_controlplane_proto_enumTypes,
		MessageInfos:      file_api_proto_controlplane_proto_msgTypes,
	}.Build()
	File_api_proto_controlplane_proto = out.File
	file_api_proto_controlplane_proto_goTypes = nil
	file_api_proto_controlplane_proto_depIdxs = nil
}
